### ISSUE TITLE
ButtonVariant is missing enum value for secondary

### ISSUE THREAD

**Issue by Wnt** [vaadin/vaadin-button-flow#116]
There is `ButtonVariant.LUMO_PRIMARY` and `ButtonVariant.LUMO_TERTIARY` but none for secondary.

**Comment by Legioth** [comment]
The secondary style is the default that is used whenever neither of primary or tertiary is defined. There is no specific theme variant value for it: https://github.com/vaadin/vaadin-button/blob/master/theme/lumo/vaadin-button-styles.html doesn't have any selectors for `[theme~="secondary"]`.
