### ISSUE TITLE
disableOnClick not working when button is detached and attached again

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-button-flow#169]
Based on https://stackoverflow.com/questions/63634513/reliability-of-button-disableonclick-in-vaadin-14

Basically the initialization code `initDisableOnClick` should be executed always when the button is attached. Currently it is easily broken when either `@PreserveOnRefresh` is used or when the button is inside a dialog that is closed and reopened.

**Comment by tomivirkki** [comment]
Closing as a duplicate of https://github.com/vaadin/vaadin-button-flow/issues/171
