### ISSUE TITLE
When a user clicks a button, I want to be able to disable it immediately

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-button-flow#27]
In case the button triggers certain actions, being able to disable the button immediately (i.e. without server round-trip) would be safer to avoid a duplicate action before the first one is completed.

**Comment by heruan** [comment]
Any update on this? I'm testing a couple of Flow apps with some users and the "multiple click" behavior is quite common, explained as:

- "double click" (bad) habit of the user;
- the user is uncertain if she clicked or not the button;
- the user thinks the app has "missed" the request, since the response isn't immediate.

This would be really useful before RC.

**Comment by Artur-** [comment]
Can this be hacked using event data, in the same way as controlling propagation behavior?

**Comment by mstahv** [comment]
The old API we had in previous version: https://vaadin.com/api/com/vaadin/ui/Button.html#setDisableOnClick-boolean-

**Comment by knoobie** [comment]
SetDisableOnClick is a must have. Most of our application used it for example something like this:

- User clicked button with a long running process 
- disableOnClick was called -> I applied additional styling to the button and the label changed from "Save" to "Spinning Icon" 
- Action was done -> button was enabled again and the User had a great UX

**Comment by evanzel** [comment]
I just started migration and stumbled upon this. I would not want to miss this.
