### ISSUE TITLE
Use prefix and suffix slots for icons

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-button-flow#37]
`<vaadin-button>` introduced slots for icons used together with text (on the same line).

See examples here (last example): https://cdn.vaadin.com/vaadin-button/2.0.0-alpha5/demo/#button-basic-demos

For icon-only buttons, don’t use a slot, and add `theme="icon"` (like currently).

**Comment by pleku** [comment]
I don't know why I've determined at some point that this is not a bug, as the slot for icons has been there in the 2.0 version which is used in 1.0 version of the Java integration.

**Comment by pekam** [comment]
The fix will be included in `vaadin-button-flow` version 2.0 for Vaadin 14.

At least for now, we are not planning to backport it for Vaadin 10, as using the slots affects the styles a bit. It might give unexpected results for users who have added custom styling as a workaround for the old behavior.
