### ISSUE TITLE
Allow keybindings for button

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/vaadin-button-flow#46]
Framework 8 had a convenience method `setClickShortcut()` for binding keyboard shortcuts to buttons. I would like to see a similar feature in the new Button API.

**Comment by heruan** [comment]
I'd like to see a global shortcut API, e.g. "when *shortcut* then *action*`, not only for buttons. The then button may have a convenient method that use the shortcut API.

**Comment by heruan** [comment]
Note also that for the use case of "press enter to submit the form" the click shortcut on a button must be discouraged, as it most probably should work only when focusing certain fields (not anywhere on the page). For cases like this it would be more appropriate to set a `keypress` listener on the fields (see vaadin/vaadin-text-field-flow/pull/48).

**Comment by mstahv** [comment]
In older Vaadin versions this was just a shorthand to add it to a Panel or Window/UI (where shortcuts were registered), which triggered the same action as in the button. A really handy helper.

The basic functionality is already there in Flow, if one figures out to implement KeyNotifier.  Maybe UI and maybe Dialog could implement it?

**Comment by pleku** [comment]
This will happen as part of vaadin/flow/issues/4893 as there will be ways for
- setting click shortcuts for buttons
- focus shortcuts for focusable components
- global shortcuts

**Comment by pleku** [comment]
We should add a demo to the ButtonView about adding a click shortcut.

**Comment by lgoio** [comment]
I use UI shortcuts to trigger the click-events 
    UI.getCurrent().addShortcut(button::click, Key.ENTER);
