### ISSUE TITLE
Broken image in Vaadin Button Java example

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-button-flow#49]
@Peppe commented on [Tue Mar 27 2018](https://github.com/vaadin/platform/issues/117)

I'm not sure to which repo or team the Java API, and their examples are, so I write this generally to the platform. 

On https://vaadin.com/components/vaadin-button/java-examples, there is a broken image which looks bad. 

![screen shot 2018-03-27 at 11 21 53](https://user-images.githubusercontent.com/525503/37955365-17070268-31b1-11e8-91e8-4ae406e02753.png)

**Comment by ZheSun88** [comment]
This should be related to https://github.com/vaadin/flow-component-base/issues/44 and had been fixed by https://github.com/vaadin/flow-component-base/pull/45. I will ask the Vcom team to confirm that.

**Comment by ZheSun88** [comment]
https://vaadin.com/components/vaadin-button/java-examples

working now. issue closed
