### ISSUE TITLE
Make Button OSGi compatible bundle

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-button-flow#88]
Split out from vaadin/flow#4630, to first research:
- what should be added to vaadin/flow-component-base
- what should be added to the component vaadin/vaadin-button-flow 
to make it OSGi compatible.

(For clarity, this is just about the component itself, not about the static resources or webjars)

**Comment by denis-anisimov** [comment]
The final result of this should be OSGi compatible MANIFEST.MF file packaged along with the jar file.

**Comment by denis-anisimov** [comment]
To do this you should use the plugin which generates the bundle file based on the template.
See the example here: https://github.com/vaadin/flow/blob/master/pom.xml#L399

The bundle file template is called `bnd.bnd`  and should be in the root of the module.
Example : https://github.com/vaadin/flow/blob/master/flow-server/bnd.bnd

Don't forget to include the generated MANIFEST into the JAR file:
https://github.com/vaadin/flow/blob/master/flow-server/pom.xml#L171
